version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: user
  MYSQL_PASSWORD: password
  MYSQL_DATABASE: studentdb
  ANGULAR_APP_SERVER_PORT: 8000

services:
  mysql:
    image: mysql:5.7
    container_name: mysql1
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./db/student.sql:/docker-entrypoint-initdb.d/student.sql
      - ./docker-runtime/db/data:/var/lib/mysql # I gestisco i dati localmente



  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    links:
      - mysql:mysql
    ports:
      - 8080:80
    restart: always


  server:
    build: ./server
    depends_on:
      - mysql
    expose:
      - 8000
      - 9200
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql
    ports:
      - 8000:8000
      - 9200:9200
    volumes:
      - ./server:/app
    links:
      - mysql
    command: npm start
    
